[package]
name = "variant_sudoku"
version = "0.1.0"
edition = "2021"

[lib]
name = "variant_sudoku"
path = "src/lib.rs"

[dependencies]
grid = "0.18.0"
itertools = "0.14.0"
log = "0.4.27"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
thiserror = "2.0.12"
